FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN dpkg --add-architecture arm64
RUN apt-get update && \
    apt-get install -y \
        git \
        make \
        g++-aarch64-linux-gnu \
        libstdc++-12-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN git clone --depth 1 \
    https://github.com/hzeller/rpi-rgb-led-matrix.git

WORKDIR /opt/rpi-rgb-led-matrix
RUN make \
    CC=aarch64-linux-gnu-gcc \
    CXX=aarch64-linux-gnu-g++ \
    AR=aarch64-linux-gnu-ar

ENV CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
ENV CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
ENV AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar
ENV CC=aarch64-linux-gnu-gcc
ENV CXX=aarch64-linux-gnu-g++